"""Play an `audioinstruments` module inside the sidecar.

The instrument library lives in audioif now, where it knows nothing about
this plug-in: an instrument is a `create(sample_rate, transport=None)`
factory returning an object with `note_on`/`note_off`/`set_macro`/
`program_change` and an `output` to pull PCM from. This module is the one
place that knows both halves. It binds such a factory to `vstaudio`, so a
script here shrinks to two lines:

    import mpvst_adapter
    mpvst_adapter.run("audioinstruments.tr808")

`lib/instruments/*.py` are exactly that, generated by
`tools/generate_shims.py`. The soundtrack's piece-private instruments keep
their bodies and call `attach(create)` from a `__main__` guard instead,
because those files *are* the patches and are meant to be read and edited
in place.

Units are the reason this file exists. `vstaudio` hands out normalized
0.0-1.0 floats, which is what the VST3 parameter API speaks; the
instrument API speaks MIDI 0-127, which is what a keyboard, a sequencer
and a saved patch speak. The conversion happens here, once, at the seam -
and it is a multiply, not a quantization, so a host automating a macro
with more than 7 bits of resolution keeps every bit of it.
"""

import sys

import vstaudio


def attach(create):
    """Build an instrument from `create` and wire it to the host.

    Returns the instrument, so a private script can keep a reference and
    poke at it - the soundtrack's `check_pump.py` does exactly that.
    """
    instrument = create(vstaudio.sample_rate(), transport=vstaudio.transport)

    def dispatch(event_type, channel, note_id, data0, value0, value1,
                 sample_position):
        if event_type == vstaudio.EVENT_NOTE_ON:
            # `value1` is a fractional pitch offset in semitones, already in
            # the units the instrument API wants - the host's own detune,
            # not something scaled to a controller range.
            instrument.note_on(data0, value0 * 127.0, value1, channel,
                               note_id, sample_position)
        elif event_type == vstaudio.EVENT_NOTE_OFF:
            instrument.note_off(data0, channel, note_id, sample_position)
        elif event_type == vstaudio.EVENT_PARAMETER:
            instrument.set_macro(data0, value0 * 127.0, channel, note_id,
                                 sample_position)
        elif event_type == vstaudio.EVENT_PROGRAM_CHANGE:
            instrument.program_change(data0, channel, note_id,
                                      sample_position)
        elif event_type == vstaudio.EVENT_CHANNEL_PRESSURE:
            instrument.channel_pressure(value0 * 127.0, channel,
                                        sample_position)
        elif event_type == vstaudio.EVENT_POLY_PRESSURE:
            instrument.poly_pressure(data0, value0 * 127.0, channel, note_id,
                                     sample_position)
        # PITCH_BEND, CONTROL_CHANGE and TRANSPORT are deliberately not
        # forwarded: no instrument in the library reads them. Transport is
        # not an event to these instruments at all - the ones that sync to
        # tempo call the `transport` callable when they need a reading,
        # which is why it is passed to `create` above.

    vstaudio.on_event(dispatch)
    vstaudio.output(instrument.output)
    return instrument


def run(module_name):
    """Import `module_name` fresh and attach its `create`."""
    # The sidecar reloads a script by re-exec'ing this file, but an import
    # is cached: without this, editing an instrument and hitting reload
    # would rebuild the old code. Drop the whole library rather than just
    # the named module, so an edit to a shared helper counts as a reload
    # too. Costs a wavetable rebuild, which is what a reload is for.
    root = module_name.split(".")[0]
    for cached in list(sys.modules):
        if cached == root or cached.startswith(root + "."):
            del sys.modules[cached]
    __import__(module_name)
    return attach(sys.modules[module_name].create)
