"""Run an `audioeffects` class inside the sidecar.

The instrument twin of this is `mpvst_adapter`, and the split is the same:
the effect library lives in audioif and knows nothing about this plug-in, so
this module is the one place that knows both halves. An effect is a class
taking the audio it should process as its first argument and exposing an
`output` to pull from, which is exactly what `vstaudio.input()` and
`vstaudio.output()` provide.

    import mpvst_effect_adapter
    mpvst_effect_adapter.run("TapeDelay")

`lib/effects/*.py` are that line, generated by `tools/generate_shims.py`.

Macros work the same way they do for instruments - normalized 0.0-1.0 on the
wire, MIDI 0-127 to the library - but not every effect has knobs yet. A class
without `MACRO_LABELS` has no patch surface at all and `set_macro` raises
rather than pretending, so this checks once at attach and simply does not
wire the parameter path for those. They still process audio; their sliders
just do nothing until audioif gives them a surface.
"""

import sys

import vstaudio

# What the last `attach` built, and where it came from. The editor panel reads
# these for its labels and patch list, the same way it does for instruments.
effect = None
module_name = None
class_name = None


def attach(cls, **kwargs):
    """Build `cls` around the host's input bus and wire it to the output."""
    global effect
    effect = cls(vstaudio.input(), **kwargs)

    if getattr(cls, "MACRO_LABELS", ()):
        def dispatch(event_type, channel, note_id, data0, value0, value1,
                     sample_position):
            # Effects take no notes. A parameter change is the only event
            # that means anything here, and only for a class with knobs.
            if event_type == vstaudio.EVENT_PARAMETER:
                effect.set_macro(data0, value0 * 127.0)

        vstaudio.on_event(dispatch)

    vstaudio.output(effect.output)
    return effect


def run(name, **kwargs):
    """Import `audioeffects` fresh and attach the class called `name`."""
    global module_name, class_name
    # Same reason as the instrument adapter: a reload re-execs the script, but
    # an import is cached, so an edit to the library would not be picked up
    # without dropping the whole package first.
    for cached in list(sys.modules):
        if cached == "audioeffects" or cached.startswith("audioeffects."):
            del sys.modules[cached]
    import audioeffects

    cls = getattr(audioeffects, name, None)
    if cls is None:
        raise ImportError("audioeffects has no %s" % name)
    module_name = "audioeffects"
    class_name = name
    return attach(cls, **kwargs)
