"""Run an `audioeffects` component inside the sidecar.

The instrument twin of this is `mpvst_adapter`, and the split is the same:
the effect library lives in audioif and knows nothing about this plug-in, so
this module is the one place that knows both halves. An effect factory takes
the host input and sample rate and returns an object exposing an `output` to
pull from, which is exactly what `vstaudio.input()` and `vstaudio.output()`
provide.

    import mpvst_effect_adapter
    mpvst_effect_adapter.run("TapeDelay")

`lib/effects/*.py` are that line, generated by `tools/generate_shims.py`.

The adapter calls `audioeffects.create(name, source, sample_rate, **kwargs)`;
it does not instantiate an effect class directly. That package factory is the
audioif component factory boundary.

Macros work the same way they do for instruments - normalized 0.0-1.0 on the
wire, MIDI 0-127 to the library. The provider declares an empty macro surface
explicitly when an effect has no knobs; this consumer remains tolerant and
simply does not wire the parameter path for one. Such an effect still
processes audio, while a provider with macros receives those events here.
"""

import sys

import vstaudio

# What the last `attach` built, and where it came from. The editor panel reads
# these for its labels and patch list, the same way it does for instruments.
effect = None
module_name = None
class_name = None


def attach(factory, **kwargs):
    """Build a component through its factory around the host input bus."""
    global effect
    effect = factory(vstaudio.input(), vstaudio.sample_rate(), **kwargs)

    if (getattr(effect, "MACRO_LABELS", ())
            or getattr(effect, "PATCHES", {})):
        def dispatch(event_type, channel, note_id, data0, value0, value1,
                     sample_position):
            # Effects take no notes. A parameter change is the only event
            # that means anything here, and patches are the one other
            # component event an effect may consume.
            if event_type == vstaudio.EVENT_PARAMETER:
                effect.set_macro(data0, value0 * 127.0)
            elif event_type == vstaudio.EVENT_PROGRAM_CHANGE:
                effect.program_change(data0)

        vstaudio.on_event(dispatch)

    vstaudio.output(effect.output)
    return effect


def run(name, **kwargs):
    """Import `audioeffects` fresh and attach the effect called `name`."""
    global module_name, class_name
    # Same reason as the instrument adapter: a reload re-execs the script, but
    # an import is cached, so an edit to the library would not be picked up
    # without dropping the whole package first.
    for cached in list(sys.modules):
        if cached == "audioeffects" or cached.startswith("audioeffects."):
            del sys.modules[cached]
    import audioeffects

    def factory(source, sample_rate, **options):
        return audioeffects.create(name, source, sample_rate, **options)

    module_name = "audioeffects"
    class_name = name
    return attach(factory, **kwargs)
