# mpvst-macro-labels: Volume | Filter 1 Cutoff | Filter 2 Cutoff | Filter Mix | Resonance 1 | Resonance 2 | Env 1 -> F1 | Env 1 -> F2 | Unison Detune | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Attack | Filter Decay | Master Tune
# mpvst-module: audioinstruments.andromeda
"""Alesis Andromeda A6.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/andromeda.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.andromeda")
