# mpvst-macro-labels: Volume | VCF Cutoff | Resonance | FM Amount | Reverb Mix | Osc 2 Detune | Osc 3 Detune | Env 1 Attack | Env 1 Release | Env 2 Attack | Env 2 Decay | Env 2 Sustain | Env 2 Release | VCA Attack | VCA Release | Master Tune
# mpvst-module: audioinstruments.arp2600
"""ARP 2600.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/arp2600.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.arp2600")
