# mpvst-macro-labels: Volume | Drawbar 16 | Drawbar 8 | Drawbar 4 | Drawbar 2 | Perc Level | Perc Decay | Key Click | Leslie Fast | Overdrive | Master Tune
# mpvst-module: audioinstruments.b3
"""Hammond B-3 tonewheel organ.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/b3.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.b3")
