# mpvst-macro-labels: Volume | Pickup Mix | Mute Level | Wah Depth | Wah Rate | Brilliance | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.clavinet
"""Hohner Clavinet D6.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/clavinet.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.clavinet")
