# mpvst-macro-labels: Volume | Hammer Strike | String Body | Tremolo Rate | Tremolo Depth | Chorus | Decay | Brilliance | Master Tune
# mpvst-module: audioinstruments.cp70
"""Yamaha CP-70 electric grand.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/cp70.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.cp70")
