# mpvst-macro-labels: Level | Accent | BD Decay | BD Pitch | SD Snappy | SD Pitch | Rim Level | Bongo Hi | Bongo Lo | Claves Level | Cowbell Level | Guiro Level | Tamb Level | Maracas Level | Metal Beat | Hat Tone
# mpvst-module: audioinstruments.cr78
"""Roland CR-78 CompuRhythm.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/cr78.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.cr78")
