# mpvst-macro-labels: Volume | VCF Cutoff | Resonance | HPF Cutoff | Ring Mod Speed | Ring Mod Depth | Layer II Mix | Poly AT Depth | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Attack | Filter Decay | Filter Sustain | Brilliance
# mpvst-module: audioinstruments.cs80
"""Yamaha CS-80.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/cs80.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.cs80")
