# mpvst-macro-labels: Volume | PD Env Depth | PD Attack | PD Decay | Resonance (Fake) | Vibrato Rate | Vibrato Depth | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.cz101
"""Casio CZ-101 phase distortion synthesizer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/cz101.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.cz101")
