# mpvst-macro-labels: Volume | Transient Mix | Synth Mix | Transient Tune | Cutoff | Resonance | Chorus | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.d50
"""Roland D-50 linear synthesizer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/d50.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.d50")
