# mpvst-macro-labels: Level | BD Pitch | BD Decay | SD Pitch | SD Snappy | Rim Pitch | Clap Decay | LT Pitch | MT Pitch | HT Pitch | Tambourine | Shaker | Cowbell | Cymbal Pitch | CH Decay | OH Decay
# mpvst-module: audioinstruments.dmx
"""Oberheim DMX.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/dmx.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.dmx")
