# mpvst-macro-labels: Volume | Kick Pitch | Snare Pitch | HiHat Pitch | Tom Pitch | Crunch Level | Overall Decay | Master Tune
# mpvst-module: audioinstruments.drumtraks
"""Sequential Circuits Drumtraks.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/drumtraks.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.drumtraks")
