# mpvst-macro-labels: Volume | FM Amount | Mod Ratio | Feedback | Env 1 Decay | Env 2 Decay | Env 3 Decay | Release Time | Alg Mix | Attack Time | Brightness | Tremolo Depth | Vibrato Depth | Tremolo Rate | Vibrato Rate | Master Tune
# mpvst-module: audioinstruments.dx7
"""Yamaha DX7.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/dx7.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.dx7")
