# mpvst-macro-labels: Volume | Breath Noise | Tone Brilliance | Attack | Decay | Sustain | Release | Vibrato Rate | Vibrato Depth | Filter Env | Master Tune
# mpvst-module: audioinstruments.emulator2
"""E-mu Emulator II.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/emulator2.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.emulator2")
