# mpvst-macro-labels: Volume | Patch Select | Bitcrush Approx | Attack | Decay | Sustain | Release | Pitch Env Depth | Filter Env | Master Tune
# mpvst-module: audioinstruments.fairlight
"""Fairlight CMI.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/fairlight.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.fairlight")
