# mpvst-macro-labels: Volume | Bass | Strings | Flute | Oboe | Trumpet | Multi-Tone Booster | Vibrato Rate | Vibrato Depth | Master Tune
# mpvst-module: audioinstruments.farfisa
"""Farfisa Compact combo organ.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/farfisa.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.farfisa")
