# mpvst-macro-labels: Volume | Vowel A | Vowel B | Morph Speed | FM Index | Brightness | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.fs1r
"""Yamaha FS1R formant synthesizer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/fs1r.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.fs1r")
