# mpvst-macro-labels: Volume | Cutoff | Resonance | Supersaw Detune | Supersaw Mix | Env Depth | Chorus | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Attack | Filter Decay | Filter Sustain | HPF Cutoff | Master Tune
# mpvst-module: audioinstruments.jp8000
"""Roland JP-8000.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/jp8000.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.jp8000")
