# mpvst-macro-labels: Volume | Cutoff | Resonance | Sub Level | Noise Level | Chorus Depth | Chorus Rate | HPF | PWM Amount | LFO Rate | Env Depth | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Decay
# mpvst-module: audioinstruments.juno106
"""Roland Juno-106.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/juno106.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.juno106")
