# mpvst-macro-labels: Volume | Cutoff | Resonance | Env Depth | Cross Mod | Unison | LFO Rate | Amp Release | Amp Attack | Amp Decay | Amp Sustain | Filter Attack | Filter Decay | Filter Sustain | HPF Cutoff | PW
# mpvst-module: audioinstruments.jupiter8
"""Roland Jupiter-8.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/jupiter8.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.jupiter8")
