# mpvst-macro-labels: Volume | Layer 1 Mix | Layer 2 Mix | Layer 3 Mix | Layer 4 Mix | Shimmer Delay | Master Cutoff | Master Resonance | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Mod Wheel | Modulation Rate | Modulation Depth | Master Tune
# mpvst-module: audioinstruments.k2600
"""Kurzweil K2600.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/k2600.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.k2600")
