# mpvst-macro-labels: Volume | Pluck Position | String Damping | Body Resonance | Pick Hardness | Decay | Master Tune
# mpvst-module: audioinstruments.karplus
"""Plucked string, Karplus-Strong style.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/karplus.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.karplus")
