# mpvst-macro-labels: Level | BD Pitch | BD Decay | SD Pitch | SD Snappy | Rim Pitch | Clap Decay | LT Pitch | MT Pitch | HT Pitch | Conga Pitch | Cowbell | Tambourine | Cabasa | CH Decay | OH Decay
# mpvst-module: audioinstruments.linndrum
"""Linn LinnDrum.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/linndrum.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.linndrum")
