# mpvst-macro-labels: Volume | Tone | Flutter Rate | Flutter Depth | Attack | Release | Tape Hiss | Master Tune
# mpvst-module: audioinstruments.mellotron
"""Mellotron M400.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/mellotron.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.mellotron")
