# mpvst-macro-labels: Volume | Wavetable Pos | Cutoff | Resonance | Env to WT | Env to Filter | Filter Attack | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.microwave
"""Waldorf Microwave.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/microwave.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.microwave")
