# mpvst-macro-labels: Volume | Cutoff | Resonance | Env Amount | Glide | Osc2 Detune | Osc3 Detune | Noise Mix | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Attack | Filter Decay | Filter Sustain | Overdrive
# mpvst-module: audioinstruments.minimoog
"""Moog Minimoog Model D.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/minimoog.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.minimoog")
