# mpvst-macro-labels: Volume | HPF Cutoff | HPF Peak | LPF Cutoff | LPF Peak | Osc2 Pitch | EG2 Sweep | EG2 Attack | EG2 Decay | EG2 Sustain | EG2 Release | Ring Mod | Noise Level | VCA Attack | VCA Release | Master Tune
# mpvst-module: audioinstruments.ms20
"""Korg MS-20.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/ms20.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.ms20")
