# mpvst-macro-labels: Volume | Osc Waveform | Cutoff | Resonance | Mod Seq Rate | Mod Seq Depth | Distortion | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.ms2000
"""Korg MS2000.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/ms2000.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.ms2000")
