# mpvst-macro-labels: Volume | Timbre Wavefold | FM Index | Mod Osc Freq | LPG Strike | LPG Decay | Amp Attack | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.music_easel
"""Buchla Music Easel.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/music_easel.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.music_easel")
