# mpvst-macro-labels: Volume | Cutoff | Resonance | FM Amount | Osc Sync | Morph 1 | Morph 2 | Morph 3 | Morph 4 | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Filter Attack | Filter Decay | Filter Sustain
# mpvst-module: audioinstruments.nord_lead
"""Clavia Nord Lead.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/nord_lead.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.nord_lead")
