# mpvst-macro-labels: Volume | Detune Spread | Cutoff | Resonance | Env Depth | Brass Attack | Brass Decay | Amp Attack | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.obxa
"""Oberheim OB-Xa.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/obxa.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.obxa")
