# mpvst-macro-labels: Volume | Cutoff | Resonance | Ring Mod | LFO Rate | Env Sweep | Osc 2 Detune | Sync | Attack | Decay | Sustain | Release | HPF Cutoff | PPC | Master Tune | Glide
# mpvst-module: audioinstruments.odyssey
"""ARP Odyssey.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/odyssey.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.odyssey")
