# mpvst-macro-labels: Volume | Pluck Attack | Mellow Tone | Decay Time | Vibrato Rate | Vibrato Depth | Amp Attack | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.pianet
"""Hohner Pianet.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/pianet.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.pianet")
