# mpvst-macro-labels: Volume | Sub-Osc Level | Cutoff | Resonance | Ensemble Depth | PWM Rate | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.polysix
"""Korg Polysix.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/polysix.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.polysix")
