# mpvst-macro-labels: Volume | Wavetable Index | Cutoff | Resonance | Env Amount | Filter Attack | Filter Decay | Amp Attack | Amp Sustain | Amp Release | Detune | Master Tune
# mpvst-module: audioinstruments.ppg_wave
"""PPG Wave 2.2.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/ppg_wave.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.ppg_wave")
