# mpvst-macro-labels: Volume | Cutoff | Resonance | Env Amount | Poly Mod | Osc2 Detune | Sync | Release | Amp Attack | Amp Decay | Amp Sustain | Filter Attack | Filter Decay | Filter Sustain | LFO Rate | LFO Depth
# mpvst-module: audioinstruments.prophet5
"""Sequential Circuits Prophet-5.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/prophet5.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.prophet5")
