# mpvst-macro-labels: Volume | Joystick X | Joystick Y | Cutoff | Resonance | Env Amount | Chorus | Filter Attack | Filter Decay | Filter Sustain | Filter Release | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.prophet_vs
"""Sequential Circuits Prophet VS vector synthesizer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/prophet_vs.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.prophet_vs")
