# mpvst-macro-labels: Volume | Tine Level | Body Level | Tremolo Rate | Tremolo Depth | Overdrive | Tone | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Key-Off Noise | Master Tune
# mpvst-module: audioinstruments.rhodes
"""Fender Rhodes electric piano.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/rhodes.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.rhodes")
