# mpvst-macro-labels: Volume | Pulse Width | Sub-Osc Level | Cutoff | Resonance | Env Depth | Fast Decay | Master Tune
# mpvst-module: audioinstruments.sh101
"""Roland SH-101.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/sh101.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.sh101")
