# mpvst-macro-labels: Level | Click Level | BD Pitch | BD Sweep | BD Decay | SD Pitch | SD Sweep | SD Decay | LT Pitch | MT Pitch | HT Pitch | Tom Sweep | Tom Decay | Noise Tone | Noise Level | Cymbal Decay
# mpvst-module: audioinstruments.simmons_sdsv
"""Simmons SDS-V.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/simmons_sdsv.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.simmons_sdsv")
