# mpvst-macro-labels: Volume | Violin Mix | Viola Mix | Cello Mix | Chorus Depth | Attack | Release | Crescendo | Master Tune
# mpvst-module: audioinstruments.solina
"""ARP/Eminent Solina String Ensemble.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/solina.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.solina")
