# mpvst-macro-labels: Volume | Kick Pitch | Kick Ring | Snare Pitch | Snare Snap | Hihat Pitch | SP Crunch | Master Tune
# mpvst-module: audioinstruments.sp1200
"""E-mu SP-1200.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/sp1200.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.sp1200")
