# mpvst-macro-labels: Volume | Osc B Detune | Glide | Cutoff | Resonance | Env Mod | Beat Freq | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.taurus
"""Moog Taurus bass pedals.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/taurus.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.taurus")
