# mpvst-macro-labels: Volume | Tuning | Cutoff | Resonance | Env Mod | Decay | Accent | Overdrive | Master Tune
# mpvst-module: audioinstruments.tb303
"""Roland TB-303 Bass Line.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/tb303.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.tb303")
