# mpvst-macro-labels: Level | Accent | BD Level | BD Decay | BD Pitch | SD Level | SD Snappy | SD Pitch | LT Pitch | HT Pitch | Cym Level | Cym Decay | Cym Tone | Hat Level | CH Decay | OH Decay
# mpvst-module: audioinstruments.tr606
"""Roland TR-606 Drumatix.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/tr606.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.tr606")
