# mpvst-macro-labels: Volume | Kick Level | Snare Level | Tom Level | HiHat Level | Crash Level | Overall Decay | Master Tune
# mpvst-module: audioinstruments.tr707
"""Roland TR-707 Rhythm Composer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/tr707.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.tr707")
