# mpvst-macro-labels: Level | Accent | BD Tune | BD Decay | BD Tone | SD Tune | SD Snappy | SD Tone | Low Tom | Mid Tom | Hi Tom | Clap Decay | Cowbell | Cymbal Decay | CH Decay | OH Decay
# mpvst-module: audioinstruments.tr808
"""Roland TR-808 Rhythm Composer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/tr808.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.tr808")
