# mpvst-macro-labels: Level | Accent | BD Tune | BD Attack | BD Decay | SD Tune | SD Tone | SD Snappy | LT Tune | MT Tune | HT Tune | Tom Decay | Clap/Rim | CH Decay | OH Decay | Cymbal Tune
# mpvst-module: audioinstruments.tr909
"""Roland TR-909 Rhythm Composer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/tr909.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.tr909")
