# mpvst-macro-labels: Volume | Hypersaw Detune | Sub Osc | Cutoff | Resonance | Distortion | Env Depth | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.virus
"""Access Virus.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/virus.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.virus")
