# mpvst-macro-labels: Volume | Breath Pressure | Embouchure | Growl Rate | Growl Depth | Attack | Decay | Sustain | Release | Master Tune
# mpvst-module: audioinstruments.vl1
"""Yamaha VL1 physical modelling synthesizer.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/vl1.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.vl1")
