# mpvst-macro-labels: Volume | Drawbar 16 | Drawbar 8 | Drawbar 4 | Drawbar IV | Vibrato Rate | Vibrato Depth | Brilliance | Master Tune
# mpvst-module: audioinstruments.vox_continental
"""Vox Continental combo organ.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/vox_continental.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.vox_continental")
