# mpvst-macro-labels: Volume | Male Choir | Female Choir | Chorus Depth | Attack | Release | Formant Shift | Vibrato Rate | Vibrato Depth | Brilliance | Bass | Master Tune
# mpvst-module: audioinstruments.vp330
"""Roland VP-330 Vocoder Plus.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/vp330.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.vp330")
