# mpvst-macro-labels: Volume | Filter Mode | Cutoff | Resonance | Noise Level | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.wasp
"""EDP Wasp.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/wasp.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.wasp")
