# mpvst-macro-labels: Volume | Bite | Bark | Tremolo Rate | Tremolo Depth | Amp Attack | Amp Decay | Amp Sustain | Amp Release | Master Tune
# mpvst-module: audioinstruments.wurlitzer
"""Wurlitzer 200A electric piano.

Generated by tools/generate_shims.py - do not edit. The instrument is
audioinstruments/wurlitzer.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("audioinstruments.wurlitzer")
