#!/usr/bin/env python3
"""Write lib/instruments/*.py: one loader per audioinstruments module.

The instruments themselves live in audioif now. What this repository still
needs is a *file* per instrument, because that is the unit the plug-in
deals in: the browser lists script files, `Controller::setComponentState`
parses macro labels out of the embedded source, and a generated REAPER
project embeds the bytes of the chosen script in its plug-in state. A
shim keeps all of that working without keeping a second copy of the
instrument.

    generate_shims.py            rewrite every shim
    generate_shims.py --check    fail if any is stale (a ctest runs this)

The macro-label line is synthesized from the module's `MACRO_LABELS`, so
labels stay in one place - the instrument - and reach the plug-in, the
project generator and the patch deriver without any of them importing
audioif.

Reads the modules with `ast` rather than importing them: this runs during
project generation and in CI, where synthio may not be importable, and a
module that fails to import should be a loud error from the tests rather
than a silently missing shim.
"""

import argparse
import ast
from pathlib import Path
import sys

REPO = Path(__file__).resolve().parent.parent
INSTRUMENTS = REPO / "lib" / "instruments"
# A sibling audioif checkout is the source these are generated from; fall
# through to an installed wheel when there is none. Same rule as harness.py.
sys.path.insert(0, str(REPO.parent / "audioif" / "lib"))

PACKAGE = "audioinstruments"

TEMPLATE = '''\
# mpvst-macro-labels: {labels}
# mpvst-module: {package}.{name}
"""{summary}

Generated by tools/generate_shims.py - do not edit. The instrument is
{package}/{name}.py in audioif; edit it there and regenerate.
"""

import mpvst_adapter

mpvst_adapter.run("{package}.{name}")
'''


def module_facts(path):
    """(macro labels, docstring summary) read out of a module's source."""
    tree = ast.parse(path.read_text(), str(path))
    summary = (ast.get_docstring(tree) or "").strip().split("\n")[0]
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(isinstance(t, ast.Name) and t.id == "MACRO_LABELS"
               for t in node.targets):
            return list(ast.literal_eval(node.value)), summary
    raise SystemExit("%s declares no MACRO_LABELS" % path.name)


def shim_for(package_dir, name):
    labels, summary = module_facts(package_dir / (name + ".py"))
    if not labels:
        raise SystemExit("%s has no macros" % name)
    if len(labels) > 16:
        # The plug-in exposes sixteen; a seventeenth would be silently
        # unreachable, and the label line would lie about it.
        raise SystemExit("%s declares %d macros, the plug-in has 16"
                         % (name, len(labels)))
    return TEMPLATE.format(labels=" | ".join(labels), package=PACKAGE,
                           name=name, summary=summary or name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report stale shims instead of writing them")
    args = parser.parse_args()

    try:
        import audioinstruments
    except ImportError:
        raise SystemExit(
            "cannot import audioinstruments - build or install audioif "
            "(a sibling checkout at %s is enough)"
            % (REPO.parent / "audioif"))
    package_dir = Path(audioinstruments.__file__).resolve().parent

    INSTRUMENTS.mkdir(parents=True, exist_ok=True)
    expected = {name + ".py": shim_for(package_dir, name)
                for name in audioinstruments.ALL}

    stale, written = [], 0
    for filename, source in sorted(expected.items()):
        path = INSTRUMENTS / filename
        if path.exists() and path.read_text() == source:
            continue
        stale.append(filename)
        if not args.check:
            path.write_text(source)
            written += 1

    # A module deleted from the package leaves a shim behind that would
    # still load and still fail; catch it here rather than at note-on.
    orphans = sorted(p.name for p in INSTRUMENTS.glob("*.py")
                     if p.name not in expected)
    for filename in orphans:
        if not args.check:
            (INSTRUMENTS / filename).unlink()

    if args.check:
        if stale or orphans:
            for filename in stale:
                print("stale    %s" % filename)
            for filename in orphans:
                print("orphaned %s" % filename)
            print("\nrun tools/generate_shims.py to regenerate")
            return 1
        print("%d shims, all current" % len(expected))
        return 0

    print("%d shims: %d written, %d unchanged, %d removed"
          % (len(expected), written, len(expected) - written, len(orphans)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
